name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Code ko fetch karna
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Docker Buildx setup karna
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub (Direct Username Bypass)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aahesan41  # Humne yahan direct aapka username likh diya hai
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Image build aur push karna
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            aahesan41/mental-score-prediction:latest
            aahesan41/mental-score-prediction:${{ github.sha }}
